package com.example.more

/**
 * FloatWindow 悬浮窗标识
 */
const val FLOAT_WINDOW_ALL_APP_TAG = "FLOAT_WINDOW_ALL_APP_TAG"

//无障碍服务开启和结束
const val ACCESSIBILITY_SERVICE_START_OR_DESTROY = "ACCESSIBILITY_SERVICE_START_OR_DESTROY"

//全屏高光提示窗口
const val FLOAT_WINDOW_HIGH_LIGHT_BOX = "FLOAT_WINDOW_HIGH_LIGHT_BOX"